---

- hosts: All

  tasks:

  name: update and upgrade cache
    apt:
      update_cache: yes
      upgrade: yes

  - name: Set timezone to Africa/Lagos
    tags: time
    timezone: name = Africa/Lagos

  - name: Install Apache2
    tags: Apache2
    apt:
      name: 
        - Apache2
      state: Latest

  - name: Remove index.html file
    file:
      path: /var/www/html/index.html
      state: Absent

  - name: Display hostname
    shell:  sudo echo "<h1>Hello from $(hostname -f)</h1>" >> /var/www/html/index.html
    notify: restart Apache

  handlers:
  - name:  restart Apache
      service:
        name: Apache2
        state: restarted


